
export const cars = [
  // Luxury & Sports
  {
    id: 1,
    name: "Apex GT-R",
    brand: "Apex Motors",
    category: "Sports",
    year: 2025,
    image: "/red-sports-car-side-view.jpg",
    color: "#ef4444",
    specs: {
      Engine: "3.2L Turbocharged V6",
      Power: "620 HP",
      Torque: "575 Nm",
      Acceleration: "0-100 km/h in 2.9s",
      "Top Speed": "330 km/h",
      Transmission: "9-Speed Automatic",
    },
  },
  {
    id: 2,
    name: "Quantum Sedan",
    brand: "Quantum Motors",
    category: "Luxury",
    year: 2025,
    image: "/silver-luxury-sedan-sleek.jpg",
    color: "#c0c0c0",
    specs: {
      Engine: "2.0L Hybrid Engine",
      Power: "340 HP",
      Torque: "320 Nm",
      Acceleration: "0-100 km/h in 5.8s",
      "Top Speed": "240 km/h",
      Transmission: "CVT Automatic",
    },
  },
  {
    id: 3,
    name: "Titan SUV",
    brand: "Titan Motors",
    category: "Performance",
    year: 2025,
    image: "/black-suv-premium-design.jpg",
    color: "#1f2937",
    specs: {
      Engine: "4.0L Twin-Turbo V8",
      Power: "580 HP",
      Torque: "690 Nm",
      Acceleration: "0-100 km/h in 4.2s",
      "Top Speed": "280 km/h",
      Transmission: "10-Speed Automatic",
    },
  },
  {
    id: 4,
    name: "Horizon EV",
    brand: "Horizon Motors",
    category: "Electric",
    year: 2025,
    image: "/blue-electric-car-modern.jpg",
    color: "#3b82f6",
    specs: {
      Engine: "Electric Motor",
      Power: "500 HP",
      Torque: "750 Nm",
      Acceleration: "0-100 km/h in 3.4s",
      Range: "650 km",
      "Charging Time": "20 mins (10-80%)",
    },
  },
  {
    id: 5,
    name: "Phantom Coupe",
    brand: "Prestige Motors",
    category: "Luxury",
    year: 2025,
    image: "/black-luxury-coupe-car.jpg",
    color: "#1f1f1f",
    specs: {
      Engine: "5.0L V12",
      Power: "725 HP",
      Torque: "750 Nm",
      Acceleration: "0-100 km/h in 3.2s",
      "Top Speed": "350 km/h",
      Transmission: "8-Speed Automatic",
    },
  },
  {
    id: 6,
    name: "Velocity Pro",
    brand: "Velocity Motors",
    category: "Sports",
    year: 2025,
    image: "/yellow-sports-car-racing.jpg",
    color: "#fbbf24",
    specs: {
      Engine: "4.5L Twin-Turbo V8",
      Power: "750 HP",
      Torque: "680 Nm",
      Acceleration: "0-100 km/h in 2.7s",
      "Top Speed": "360 km/h",
      Transmission: "7-Speed Manual",
    },
  },
  {
    id: 7,
    name: "Elite Sedan",
    brand: "Elite Motors",
    category: "Luxury",
    year: 2025,
    image: "/white-luxury-sedan-car.jpg",
    color: "#ffffff",
    specs: {
      Engine: "3.0L Turbocharged V6",
      Power: "450 HP",
      Torque: "420 Nm",
      Acceleration: "0-100 km/h in 4.5s",
      "Top Speed": "270 km/h",
      Transmission: "9-Speed Automatic",
    },
  },
  {
    id: 8,
    name: "Beast X7",
    brand: "Beast Motors",
    category: "Performance",
    year: 2025,
    image: "/green-powerful-suv.jpg",
    color: "#22c55e",
    specs: {
      Engine: "5.5L Twin-Turbo V10",
      Power: "850 HP",
      Torque: "920 Nm",
      Acceleration: "0-100 km/h in 3.5s",
      "Top Speed": "300 km/h",
      Transmission: "11-Speed Automatic",
    },
  },
  {
    id: 9,
    name: "Nova EV-Max",
    brand: "Nova Electric",
    category: "Electric",
    year: 2025,
    image: "/cyan-electric-car-futuristic.jpg",
    color: "#06b6d4",
    specs: {
      Engine: "Dual Electric Motors",
      Power: "600 HP",
      Torque: "850 Nm",
      Acceleration: "0-100 km/h in 2.8s",
      Range: "750 km",
      "Charging Time": "15 mins (10-80%)",
    },
  },
  {
    id: 10,
    name: "Raptor GT",
    brand: "Raptor Motors",
    category: "Sports",
    year: 2025,
    image: "/orange-sports-car-aggressive.jpg",
    color: "#f97316",
    specs: {
      Engine: "4.0L Supercharged V8",
      Power: "700 HP",
      Torque: "710 Nm",
      Acceleration: "0-100 km/h in 2.9s",
      "Top Speed": "340 km/h",
      Transmission: "8-Speed Manual",
    },
  },
  {
    id: 11,
    name: "Zenith Luxury",
    brand: "Zenith Motors",
    category: "Luxury",
    year: 2025,
    image: "/gold-luxury-car-premium.jpg",
    color: "#d4af37",
    specs: {
      Engine: "6.0L Twin-Turbo V12",
      Power: "800 HP",
      Torque: "900 Nm",
      Acceleration: "0-100 km/h in 3.0s",
      "Top Speed": "360 km/h",
      Transmission: "9-Speed Automatic",
    },
  },
  {
    id: 12,
    name: "Vortex Compact",
    brand: "Vortex Motors",
    category: "Compact",
    year: 2025,
    image: "/blue-compact-city-car.jpg",
    color: "#0ea5e9",
    specs: {
      Engine: "1.5L Turbocharged 3-Cylinder",
      Power: "200 HP",
      Torque: "210 Nm",
      Acceleration: "0-100 km/h in 7.2s",
      "Top Speed": "200 km/h",
      Transmission: "6-Speed Automatic",
    },
  },
  {
    id: 13,
    name: "Commander Off-Road",
    brand: "Commander Motors",
    category: "Performance",
    year: 2025,
    image: "/brown-off-road-suv.jpg",
    color: "#92400e",
    specs: {
      Engine: "3.8L Twin-Turbo V6",
      Power: "520 HP",
      Torque: "610 Nm",
      Acceleration: "0-100 km/h in 4.8s",
      "Top Speed": "260 km/h",
      Transmission: "10-Speed Automatic",
    },
  },
  {
    id: 14,
    name: "Bolt EV Speed",
    brand: "Bolt Motors",
    category: "Electric",
    year: 2025,
    image: "/purple-electric-car-sleek.jpg",
    color: "#a855f7",
    specs: {
      Engine: "Triple Electric Motors",
      Power: "720 HP",
      Torque: "900 Nm",
      Acceleration: "0-100 km/h in 2.5s",
      Range: "800 km",
      "Charging Time": "12 mins (10-80%)",
    },
  },
  {
    id: 15,
    name: "Crown Royal",
    brand: "Crown Motors",
    category: "Luxury",
    year: 2025,
    image: "/maroon-luxury-sedan-classic.jpg",
    color: "#7c2d12",
    specs: {
      Engine: "5.5L V12 Twin-Turbo",
      Power: "780 HP",
      Torque: "820 Nm",
      Acceleration: "0-100 km/h in 3.1s",
      "Top Speed": "355 km/h",
      Transmission: "9-Speed Automatic",
    },
  },
  {
    id: 16,
    name: "Storm RS",
    brand: "Storm Motors",
    category: "Sports",
    year: 2025,
    image: "/red-racing-car-track.jpg",
    color: "#dc2626",
    specs: {
      Engine: "3.5L Supercharged V8",
      Power: "680 HP",
      Torque: "620 Nm",
      Acceleration: "0-100 km/h in 2.85s",
      "Top Speed": "345 km/h",
      Transmission: "7-Speed DCT",
    },
  },
  {
    id: 17,
    name: "Compass Adventure",
    brand: "Compass Motors",
    category: "Performance",
    year: 2025,
    image: "/teal-adventure-suv.jpg",
    color: "#14b8a6",
    specs: {
      Engine: "4.2L V8 Hybrid",
      Power: "550 HP",
      Torque: "650 Nm",
      Acceleration: "0-100 km/h in 4.3s",
      "Top Speed": "290 km/h",
      Transmission: "10-Speed Automatic",
    },
  },
  {
    id: 18,
    name: "Pulse Electric+",
    brand: "Pulse Motors",
    category: "Electric",
    year: 2025,
    image: "/neon-green-electric-car.jpg",
    color: "#22c55e",
    specs: {
      Engine: "Quad Electric Motors",
      Power: "850 HP",
      Torque: "1000 Nm",
      Acceleration: "0-100 km/h in 2.3s",
      Range: "900 km",
      "Charging Time": "10 mins (10-80%)",
    },
  },
  {
    id: 19,
    name: "Magnum Roadster",
    brand: "Magnum Motors",
    category: "Sports",
    year: 2025,
    image: "/silver-roadster-convertible.jpg",
    color: "#d1d5db",
    specs: {
      Engine: "4.8L Twin-Turbo V10",
      Power: "770 HP",
      Torque: "740 Nm",
      Acceleration: "0-100 km/h in 2.6s",
      "Top Speed": "370 km/h",
      Transmission: "8-Speed Sequential",
    },
  },
  {
    id: 20,
    name: "Infinity Eco",
    brand: "Infinity Motors",
    category: "Compact",
    year: 2025,
    image: "/placeholder.svg?height=400&width=400",
    color: "#84cc16",
    specs: {
      Engine: "2.0L Hybrid Engine",
      Power: "280 HP",
      Torque: "300 Nm",
      Acceleration: "0-100 km/h in 6.5s",
      "Top Speed": "220 km/h",
      Transmission: "CVT Automatic",
    },
  },
]




